name: TimeFlow
options:
  bundleIdPrefix: com.tagg.timeflow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_PREVIEWS: YES

targets:
  TimeFlow:
    type: application
    platform: macOS
    sources:
      - path: TimeFlow
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tagg.timeflow
        PRODUCT_NAME: TimeFlow
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_CFBundleDisplayName: TimeFlow
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2025 Tagg. All rights reserved."
        DEVELOPMENT_ASSET_PATHS: ""

schemes:
  TimeFlow:
    build:
      targets:
        TimeFlow: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
